[package]
name = "rust-crud-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
chrono = { version = "0.4.41", features = ["serde"] }
dotenv = "0.15.0"
serde = "1.0.228"
serde_json = "1.0.150"
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-rustls-ring-webpki", "postgres", "chrono", "uuid" ] }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.17.0", features = ["serde", "v4"] }

